spring:
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: kafka:9092
      properties:
        spring.json.add-type-headers: false
    admin:
      properties:
        request.timeout.ms: 30000
      fail-fast: true

kafka:
  topics:
    audio-uploads: audio-uploads

minio:
  endpoint: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: audio-bucket
  secure: false

metadata:
  service:
    url: http://metadata-service:8010/api/v1

server:
  port: 8000
