spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      bootstrap-servers: localhost:29092
    consumer:
      bootstrap-servers: localhost:29092
    admin:
      properties:
        request.timeout.ms: 30000
      fail-fast: true

kafka:
  topics:
    audio-uploads: audio-uploads
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: audio-bucket
  secure: false
server:
  port: 8000

metadata:
  service:
    url: http://localhost:8080/api/v1