spring:
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      bootstrap-servers: kafka:29092
    consumer:
      bootstrap-servers: kafka:29092
    admin:
      properties:
        request.timeout.ms: 30000
      fail-fast: true

kafka:
  topics:
    audio-uploads: audio-uploads

minio:
  endpoint: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: audio-bucket
  secure: false

metadata:
  service:
    url: http://metadata-service:8010/api/v1

server:
  port: 8000
