spring:
  application:
    name: audio-ingestion-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}"
  cloud:
    config:
      profile: ${SPRING_PROFILES_ACTIVE:local}
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 2000
        max-attempts: 3
      request:
        read-timeout: 10000
        connect-timeout: 5000


server:
  port: 8000