spring:
  kafka:
    bootstrap-servers: kafka:9092

minio:
  url: http://minio:9000

elasticsearch:
  url: http://elasticsearch:9200

metadata:
  service:
    url: http://metadata-service:8010

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    prefer-ip-address: true