spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: audio-ingestion
          uri: lb://audio-ingestion-service
          predicates:
            - Path=/api/v1/tracks/**
          filters:
            - name: CircuitBreaker
              args:
                name: ingestionFallback
                fallbackUri: forward:/fallback/ingestion

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080