version: '3.8'

services:

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=audio_metadata
      - POSTGRES_USER=audio_admin
      - POSTGRES_PASSWORD=securepass
    ports:
      - "5432:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U audio_admin -d audio_metadata" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"


volumes:
  postgres_data:
  redis_data: