management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers
  endpoint:
    health:
      show-details: always
    loggers:
      enabled: true
  metrics:
    tags:
      application: audio-ingestion-service
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
spring:
  kafka:
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.add-type-headers: false
    admin:
      properties:
        request.timeout.ms: 30000
      fail-fast: true

kafka:
  topics:
    audio-uploads: audio-uploads

minio:
  access-key: minioadmin
  secret-key: minioadmin
  bucket: audio-bucket
  secure: false


server:
  port: 8000
