management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers
  endpoint:
    health:
      show-details: always
    loggers:
      enabled: true
  metrics:
    tags:
      application: audio-fingerprint-service

spring:
  kafka:
    consumer:
      group-id: fingerprint-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.trusted.packages: '*'

minio:
  access-key: minioadmin
  secret-key: minioadmin
  bucket: audio-bucket

metadata:
  logging:
    level:
      org.springframework.web: DEBUG
      com.audio.audiofingerprintservice: TRACE