spring:
  datasource:
    url: jdbc:postgresql://db:5432/audio_metadata

  kafka:
    bootstrap-servers: kafka:9092

minio:
  internal-url: http://minio:9000

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    prefer-ip-address: true