server:
  port: 8888


management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  metrics:
    tags:
      application: config-service


spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/${GITHUB_USERNAME}/your-config-repo.git
          search-paths: |
            configs/{application}
            username: ${GITHUB_USERNAME}
            password: ${GITHUB_TOKEN}
            clone-on-start: true
            force-pull: true
            default-label: main
        native:
          search-locations:
            - classpath:/configs/{application}