spring:
  application:
    name: audio-metadata-service

  datasource:
    url: jdbc:postgresql://db:5432/audio_metadata
    username: audio_admin
    password: securepass
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 0
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
      show-sql: true
  data:
    redis:
      host: redis
      port: 6379
      timeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

server:
  port: 8081

minio:
  url: http://localhost:9000
  access: key=your-access-key
  secret: key=your-secret-key
  bucket: audio-bucket