spring:
  datasource:
    url: jdbc:postgresql://db:5432/audio_metadata
    username: audio_admin
    password: securepass
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: redis
      port: 6379
      timeout: 5000ms
  kafka:
    bootstrap-servers: kafka:9092

minio:
  internal-url: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: audio-bucket

server:
  port: 8010
