name: Audio Ingestion Service CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_IMAGE_NAME: audio-ingestion-service

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    services:
      
      kafka:
        image: confluentinc/cp-kafka:7.3.0
        ports:
          - 9092:9092
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
        options: --health-cmd "nc -z localhost 9092 || exit 1" --health-interval 10s --health-timeout 5s --health-retries 5

      minio:
        image: minio/minio
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
        ports:
          - 9000:9000
          - 9001:9001
        command: server /data --console-address ":9001"
        options: --health-cmd "curl -f http://localhost:9000/minio/health/live || exit 1" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Run tests with Maven
      run: —Åd audio-ingestion-service && mvn clean verify
      env:
        SPRING_KAFKA_BOOTSTRAP_SERVERS: localhost:9092
        MINIO_ENDPOINT: http://localhost:9000
        MINIO_ACCESS_KEY: minioadmin
        MINIO_SECRET_KEY: minioadmin
        TESTCONTAINERS_RYUK_DISABLED: true

    

    
        
